### ISSUE TITLE
Error with tmdbTV factory

### ISSUE THREAD

**Issue by Rtransat** [Inoverse/angular-tmdb#2]
Hi,

When I use tmdbTV service, I got this error:

```Provider 'tmdbTV' must return a value from $get factory method.```

```javascript
.controller('BrowseCtrl', function($scope, tmdbTV) {
    tmdbTV.setup('my_apikey');

    tmdbTV.tv.discover(function(data) {
        console.log(data);
    });
})
```

Angular v1.3.13

**Comment by Inoverse** [comment]
Hi,
Pushed a fix for that. Get new version from master.
