### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by iulianmids** [Inoverse/angular-tmdb#5]
Hey man, have you experienced any CORS related issues?
I can't get the results in Angular due to an error:
XMLHttpRequest cannot load https://api.themoviedb.org/3/search/movie?api_key=31f815104ff2b0e3efd8998a8ecd6b28&search_type=ngram&query=300&callback=test. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true.

thanks

**Comment by Inoverse** [comment]
I'll check this out @iulianmids
