### ISSUE TITLE
Create a first release

### ISSUE THREAD

**Issue by DavidePastore** [Inoverse/angular-tmdb#6]
Hi. Could you please create a first release and publish it on npm so others can include it in `package.json`?

**Comment by DavidePastore** [comment]
Sorry but #7 doesn't fix this. I don't have the ability to publish the repo. You could follow [these steps](https://docs.npmjs.com/getting-started/publishing-npm-packages) to publish to npm your library. :ice_cream:

**Comment by Inoverse** [comment]
Oh yeah sorry. Only read the first part. This should be two issues. One for the package.json and one for the publishing.

**Comment by Inoverse** [comment]
Created release on NPM: https://www.npmjs.com/package/angular-tmdb
